[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
drift-stake-voter = "dVoTE1AJqkZVoE1mPbWcqYPmEEvAUBksHY2NiM2UJQe"

[programs.devnet]
drift-stake-voter = "dVoTE1AJqkZVoE1mPbWcqYPmEEvAUBksHY2NiM2UJQe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
